// <auto-generated />
using System;
using System.Net;
using System.Net.NetworkInformation;
using Common.BusinessLogic.DataBases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Common.Migrations
{
    [DbContext(typeof(VisitsDBContext))]
    partial class VisitsDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Common.BusinessLogic.SQLVisitorInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<IPAddress>("IP")
                        .IsRequired()
                        .HasColumnType("inet");

                    b.Property<PhysicalAddress>("MACAddress")
                        .IsRequired()
                        .HasColumnType("macaddr");

                    b.HasKey("Id");

                    b.ToTable("VisitorInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
